import '../../items/car_class.dart';

List<Car> Cars = <Car>[
  Car(
      0,
      "ЛАДА GRANTA СЕДАН",
      [
        "https://static.lada.ru/images/v6/cars/configurator/granta/sedan.webp",
        "https://static.lada.ru/images/v6/cars/tth/granta/sedan/profile_1.webp",
        "https://static.lada.ru/images/v6/cars/tth/granta/sedan/profile_2.webp",
      ],
      "LADA Granta не нужно кому-то что-то доказывать. Она уже заслужила доверие более миллиона автомобилистов и прошла проверку нашими дорогами. Не адаптированная, а разработанная специально для российских условий, LADA Granta уверена в себе на каждом километре пути. Увеличенные ходы подвесок, специальные настройки шасси и множество современных технологий делают поездки комфортными и безопасными. А благодаря широкой дилерской сети и трехлетней гарантии владельцам LADA Granta обеспечена постоянная поддержка в любом уголке страны. LADA Granta — это стильный и компактный, практичный и разносторонний помощник, союзник и друг. Такой, на которого всегда можно положиться и которому можно доверять на 100%.",
      699900,
      "	1.6 MT Classic ’22",
      "	Седан",
      "МКПП 5",
      "179",
      "5",
      "1596",
      "https://youtu.be/EJB6SRAJqNg?si=ietZ8d8dzGPImhhi"),
  Car(
      1,
      "NIVA TRAVEL",
      [
        "https://static.lada.ru/images/v6/cars/configurator/niva-travel/travel.webp",
        "https://static.lada.ru/images/v6/cars/tth/niva-travel/profile_1.webp",
        "https://static.lada.ru/images/v6/cars/tth/niva-travel/profile_2.webp",
      ],
      "Легендарный автомобиль гармонично смотрится и среди лесов, и на городских улицах. Чуть сглаженная угловатость, выразительные формы кузова, яркая светотехника, пластиковый обвес кузова — решительный характер автомобиля отражен в каждой детали.",
      1198900,
      "1.7 MT Classic",
      "	SUV",
      "МКПП 5",
      "140",
      "5",
      "1690",
      "https://youtu.be/CLww5vuaTB8?si=AIEoPaytkicLF4B0"),
  Car(
      2,
      "VESTA СЕДАН",
      [
        "https://static.lada.ru/images/v6/cars/configurator/vesta_new/sedan.webp",
        "https://static.lada.ru/images/v6/cars/tth/vesta_new/sedan/profile_1.webp",
        "https://static.lada.ru/images/v6/cars/tth/vesta_new/sedan/profile_2.webp",
      ],
      "Энергичный дизайн LADA Vesta новое поколение стал еще привлекательней. Развитый рельеф бамперов создает современный и динамичный образ автомобиля, а новая светодиодная оптика делает его по-настоящему заметным.",
      1239900,
      "1.6 MT Comfort",
      "Седан",
      "МКПП 5",
      "182",
      "5",
      "1596",
      "https://youtu.be/jg5RPqGE8z0?si=rYyxl21p4N0qcdsP"),
  Car(
      3,
      "NIVA LEGEND 3 ДВ.",
      [
        "https://static.lada.ru/images/v6/cars/configurator/niva-legend/3dv.webp",
        "https://static.lada.ru/images/v6/cars/tth/niva-legend/3dv/profile_1.webp",
        "https://static.lada.ru/images/v6/cars/tth/niva-legend/3dv/profile_2.webp",
      ],
      "LADA Niva Legend — автомобиль со всемирно известным дизайном, в котором продумана каждая деталь. Короткие свесы улучшают проходимость на пересечённой местности и позволяют безопасно парковаться вплотную к бордюрам. Компактный кузов — это удачное решение и для города, и для леса. А скругленные линии капота, дверей и колесных арок — классическое решение, актуальное всегда и везде.",
      829900,
      "1.7 MT Urban",
      "SUV",
      "МКПП 5",
      "142",
      "4",
      "1690",
      "https://youtu.be/9qVk5tH9nsM?si=sDq8D7kLe6uFsFLS"),
  Car(
      4,
      "VESTA SPORTLINE",
      [
        "https://static.lada.ru/images/v6/cars/configurator/granta/drive-active.webp",
        "https://static.lada.ru/images/v6/cars/tth/vesta_new/sportline/profile_2.webp",
        "https://static.lada.ru/images/v6/cars/tth/vesta_new/sportline/profile_1.webp",
      ],
      "Каждый маршрут становится гоночной трассой. Каждый водитель может быть самым быстрым. Силуэт — занижен, колея — расширена. Автомобиль со спортивным характером выделяется в потоке. Его слышно: выпуск настроен на свободное дыхание мотора. Под скорость создан и кузов: испытан в аэротрубе и оснащен тщательно проработанным обвесом.",
      2175900,
      "	1.6 MT 2WD Sportline",
      "Седан",
      "МКПП 5",
      "190",
      "5",
      "1596",
      "https://youtu.be/YMrs_Oi927Y?si=SAl7T92VESqTJKZR"),
  Car(
      5,
      "LARGUS CROSS",
      [
        "https://static.lada.ru/images/v6/cars/configurator/new-largus/universal.webp",
        "https://static.lada.ru/images/v6/cars/tth/new-largus/cross/profile_1.webp",
        "https://static.lada.ru/images/v6/cars/tth/new-largus/cross/profile_2.webp",
      ],
      "LADA Largus Cross взял все самое лучшее сразу от трех типов автомобиля: универсала, микроавтобуса и кроссовера. Вместительный салон, отличное оснащение, удобная высокая посадка — то, что нужно для семейных путешествий. Широкий спектр возможностей автомобиля выражен и в оригинальном стиле, который сочетает мощь и динамику. LADA Largus Cross оснащается 16-клапанным двигателем, адаптированным для работы на бензине АИ-92. Это современный, надежный и экономичный мотор, который обеспечивает хорошую динамику и комфорт движения. Опрятный и ухоженный автомобиль, в котором всегда уверен и которым приятно пользоваться. Для того, чтобы ваша LADA была именно такой, мы уже включили в состав аксессуары: ",
      2175900,
      "	1.6 MT Classic 5 мест",
      "Универсал",
      "МКПП 5",
      "160",
      "5",
      "1596",
      "https://youtu.be/sn8cOPiaD4o?si=-f95ZwaR0ByB037n"),
  Car(
      6,
      "GRANTA ФУРГОН",
      [
        "https://static.lada.ru/images/v6/cars/configurator/commercial/granta_lcv_furgon.webp",
        "https://static.lada.ru/images/v6/cars/about/granta/lcv/platform/main_desktop.jpg",
        "https://static.lada.ru/images/v6/cars/brochures/models/granta_lcv_furgon.jpg",
      ],
      "LADA Granta с бортовой платформой – надежный коммерческий автомобиль с полурамной конструкцией кузова и задней рессорной подвеской. В зависимости от задач бизнеса, можно выбрать стандартную либо удлинённую версию. Дополнительную защиту груза можно обеспечить, заказав версию со стеклопластиковым кунгом.",
      1267000,
      "	1.6 MT Classic фургон",
      "Коммерческий фургон",
      "МКПП 5",
      "158",
      "2",
      "1596",
      "https://youtu.be/Fjefua7RLgM?si=n0mRZGRXdAFzXdMr"),
];
